name: isolate_current_directory
description: Support for isolated Directory.current. Use the `withCurrentDirectory` function to change the Dart current directory within a scope without affecting the global one.
version: 2.1.0
homepage: https://github.com/renatoathaydes/isolate_current_directory

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.2

dev_dependencies:
  dartle: ^0.28.1
  file: ^7.0.1
  lints: ^4.0.0
  test: ^1.16.0
