name: isolate_current_directory
description: Support for isolated Directory.current. Use the `withCurrentDirectory` function to change the Dart current directory within a scope without affecting the global one.
version: 2.0.0
homepage: https://github.com/renatoathaydes/isolate_current_directory

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.2

dev_dependencies:
  dartle: ^0.22.2
  file: ^6.1.4
  lints: ^2.1.0
  test: ^1.16.0
